version: '3.8'
services:
  backend:
    build:
      context: ./pmt-backend    # dossier contenant le pom.xml et Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  frontend:
    build:
      context: ./pmt-frontend   # dossier contenant package.json, angular.json et Dockerfile
      dockerfile: Dockerfile
    ports:
      - "4200:80"
