name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Build, test & push backend Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and test (Maven)
        working-directory: pmt-backend
        run: mvn clean verify --file pom.xml   # Compile le projet backend et génère le JAR dans target/

      - name: Build Docker image (Backend)
        uses: docker/build-push-action@v3
        with:
          context: pmt-backend                # Contexte de build Docker = dossier backend (contient le JAR)
          file: pmt-backend/Dockerfile        # Dockerfile du backend
          push: false
      # - name: Push Backend image to registry
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: pmt-backend
      #     file: pmt-backend/Dockerfile
      #     push: true
      #     tags: your-repo/backend:latest    # (exemple d'étape pour pousser l'image, si désiré)

  frontend:
    name: Build, test & push frontend Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3              # Important: clone le dépôt pour avoir pmt-frontend/

      - name: Install dependencies
        working-directory: pmt-frontend
        run: npm install

      # - name: Run frontend tests (optional)
      #   working-directory: pmt-frontend
      #   run: npm test

      # - name: Build frontend app (optional, e.g. Angular build)
      #   working-directory: pmt-frontend
      #   run: npm run build -- --prod

      - name: Build Docker image (Frontend)
        uses: docker/build-push-action@v3
        with:
          context: pmt-frontend               # Contexte de build = dossier frontend
          file: pmt-frontend/Dockerfile       # Dockerfile du frontend
          push: false
      # - name: Push Frontend image to registry
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: pmt-frontend
      #     file: pmt-frontend/Dockerfile
      #     push: true
      #     tags: your-repo/frontend:latest   # (exemple pour pousser l'image frontend)
