name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Build, test & push backend Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Exécute Maven dans le dossier pmt-backend pour trouver le pom.xml
      - name: Build and run tests for backend
        working-directory: pmt-backend
        run: mvn clean package

      # Construit l'image Docker en utilisant le contexte "pmt-backend"
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projet-backend:latest -f pmt-backend/Dockerfile pmt-backend

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push backend image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/projet-backend:latest

  frontend:
    name: Build, test & push frontend Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Exécuter npm dans le dossier pmt-frontend pour que package.json soit trouvé
      - name: Install dependencies and run frontend tests
        working-directory: pmt-frontend
        run: |
          npm install
          npm run test -- --clearCache

      - name: Build frontend in production mode
        working-directory: pmt-frontend
        run: npm run build -- --project pmt-frontend --configuration production

      # Construit l'image Docker en utilisant le contexte "pmt-frontend"
      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/projet-frontend:latest -f pmt-frontend/Dockerfile pmt-frontend

      - name: Push frontend image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/projet-frontend:latest
